# Generated by Django 3.0.4 on 2020-03-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatbooking',
            name='time_check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
