# Generated by Django 3.0.4 on 2020-04-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200312_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('menu_pic', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('date_time_arrival', models.DateTimeField(auto_now=True)),
                ('admin_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transfering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.CreateModel(
            name='wallet_wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Transfering')),
                ('wallet_wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Wallet')),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.User'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Order')),
                ('shop_shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.User'),
        ),
        migrations.CreateModel(
            name='Order_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField(null=True)),
                ('menu_menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Menu')),
                ('order_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_wallet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Wallet'),
        ),
        migrations.AddField(
            model_name='menu',
            name='shop_shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Shop'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('menu_menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('score', models.IntegerField(null=True)),
                ('commend', models.TextField(max_length=255)),
                ('customer_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Customer')),
                ('shop_shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.User'),
        ),
        migrations.AddField(
            model_name='admin',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.User'),
        ),
    ]
